version: '3.9'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: rebbu
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    volumes:
      - rebbudb:/var/lib/postgresql/data
volumes:
  rebbudb:

